### ISSUE TITLE
build/src not created in build

### ISSUE THREAD

**Issue by amadogabriel** [cda-tum/dd_package#109]
build/src was not created in build, I've tried it both on UNIX and windows. 

<img width="849" alt="image" src="https://user-images.githubusercontent.com/75212399/191529536-6ee9d7aa-171c-402d-8ba4-b17b151bfcc5.png">

<img width="802" alt="image" src="https://user-images.githubusercontent.com/75212399/191529689-88e5fca1-a979-45e1-a873-d82c291b626a.png">

**Comment by hillmich** [comment]
Could you explain what you expected after the build process? Both calls to cmake look fine to me.

**Comment by hillmich** [comment]
That's an error in the readme, thanks for spotting that. The library is header-only (mostly because of the templates) and therefore does the build process does not produce a shared library. To use the DD package, you'll have to use `target_link_libraries` in CMake (or copy the files into your project and `#include` them in C++, albeit this makes updates harder).

**Comment by amadogabriel** [comment]
I figured that's what this repo does. Thanks for clarifying!
